### ISSUE TITLE
Web API key

### ISSUE THREAD

**Issue by McQuinge** [PVermeer/Fitbit-ExcelQuery#1]
Hi, thanks a lot for sharing this code and example.
I've got my Client ID and token in place, but it stops when I try to run the query.
It asks for a key to access api.fitbit.com that I don't understand what I should do...
Hoping you can help me.
![image](https://user-images.githubusercontent.com/42716122/44629226-5d234000-a94c-11e8-8b50-e8ba181b4622.png)

**Comment by PVermeer** [comment]
Sorry, not using Fitbit anymore + was a long time ago. Api might be changed? I know Fitbit didn't support direct access to Excel because they sell their own exports for Excel but it wasn't blocked this way. It might be now?
